import { POSITION_DESCRIPTION } from '@/shared/consts/tooltipDomainTerms'

export const BACKTEST_SUMMARY_COLUMNS_EN: Record<string, string> = {
    Name: 'Policy name from the active configuration.',
    Type: 'Policy logic type (how the strategy makes entry/exit decisions). Used for grouping.',
    Leverage: 'Configured leverage value: fixed number or dynamic if policy computes leverage internally.',
    MarginMode: 'Trade margin mode: Cross (shared wallet) or Isolated (risk limited to position margin).',
    Policy: 'Policy/strategy name this result row belongs to.',
    Margin: 'Margin mode (Cross/Isolated) used by this policy in backtest output.',
    Branch: 'Simulation branch: BASE is baseline logic, ANTI-D flips direction on risk trigger.',
    StopLoss: 'Whether this branch uses daily stop-loss: WITH_SL or NO_SL.',
    TotalPnlPct:
        'Total policy return for the period, in %. Higher is better, but it must be read together with risk (MaxDD%).',
    MaxDdPct: 'Maximum equity drawdown in % from local peak. Shows how painful the equity curve was.',
    Trades: 'Total trade count for this policy over the period. Larger samples are usually statistically more reliable.',
    WithdrawnTotal:
        'Amount of withdrawn profit in USD (if equity exceeded base capital). This is realized withdrawn gain.',
    HadLiquidation: 'Whether liquidation occurred in this branch (yes/no). Critical risk flag.',
    TradesBySource:
        'Trade split by signal source (Daily/DelayedA/DelayedB). Helps identify what actually generates activity.'
}

export const BACKTEST_SUMMARY_KEYS_EN: Record<string, string> = {
    FromDateUtc: 'Backtest window start date (UTC). All metrics are computed inside this range.',
    ToDateUtc: 'Backtest window end date (UTC).',
    SignalDays: 'Number of signal/record days included in calculations.',
    PolicyCount: 'Number of policies included in backtest.',
    BestTotalPnlPct: 'Best total return across policies for this period.',
    WorstMaxDdPct: 'Worst (largest) drawdown across policies.',
    PoliciesWithLiquidation: 'How many policies had at least one liquidation.',
    TotalTrades: 'Total trade count across all policies.',
    DailyStopPct: 'Base daily stop-loss (%). Dynamic overlay scales it only for days that pass confidence constraints.',
    DailyTpPct:
        'Base daily take-profit (%). Dynamic overlay scales it only for days with sufficient confidence evidence.',
    DynamicTpPctMin: 'Lower bound for final dynamic TP after all multipliers.',
    DynamicTpPctMax: 'Upper bound for final dynamic TP after all multipliers.',
    DynamicSlPctMin: 'Lower bound for final dynamic SL after all multipliers.',
    DynamicSlPctMax: 'Upper bound for final dynamic SL after all multipliers.',
    DynamicEvidenceMinBucketSamples: 'Minimum historical confidence-bucket samples required to enable dynamic TP/SL.',
    DynamicEvidenceMinBucketWinRate: 'Minimum historical confidence-bucket win-rate required to enable dynamic TP/SL.',
    DynamicOutOfRangeBehavior:
        'Behavior for invalid confidence: NoTrade skips the day, MinRisk uses minimum-risk profile.'
}

export const CURRENT_PREDICTION_COLUMNS_EN: Record<string, string> = {
    Политика: 'Trading policy/strategy name. Identifies which decision logic produced this row.',
    Ветка: 'BASE is baseline branch, ANTI-D is anti-direction branch on risk trigger.',
    Бакет: 'Execution bucket (daily/intraday/delayed): independent capital track with its own equity curve.',
    Bucket: 'Execution bucket (daily/intraday/delayed): independent capital track with its own equity curve.',
    Сторона: POSITION_DESCRIPTION,
    'Рискованный день': 'RiskDay flag: day marked as elevated-risk by SL logic.',
    'Есть направление': 'Whether the model has direction (long/short). If not, day becomes no-trade.',
    Пропущено: 'Flag that policy skipped this day (no-trade).',
    Направление: 'Final trade direction: LONG, SHORT, or no-trade when filters block entry.',
    Плечо: 'Effective leverage applied by policy for entry.',
    'Цена входа': 'Position entry price from report.',
    'Вход, $': 'Position entry price from report.',
    'Цена выхода': 'Actual exit price by first event (TP/SL/liquidation/window close).',
    'Выход, $': 'Actual exit price by first event (TP/SL/liquidation/window close).',
    'Причина выхода': 'First event that closed position: take-profit, stop-loss, liquidation, or forced close.',
    'Выход PnL, %': 'Return of this specific trade in %, relative to entry price.',
    'SL, %': 'Stop-loss level in % of entry price.',
    'TP, %': 'Take-profit level in % of entry price.',
    'Цена SL': 'Price level where stop-loss would trigger.',
    'Цена TP': 'Price level where take-profit would trigger.',
    'SL, $': 'Absolute instrument price at stop-loss level.',
    'TP, $': 'Absolute instrument price at take-profit level.',
    'Номинал позиции, $': 'Full position notional after leverage. Used for exposure and quantity math; it is not the same as margin.',
    'Размер позиции, qty': 'Position size in asset quantity units.',
    'Цена ликвидации': 'Estimated liquidation price for selected leverage.',
    'Цена ликвидации, $': 'Estimated liquidation price for selected leverage.',
    'Дистанция до ликвидации, %': 'Price buffer to liquidation level, in %.',
    'Капитал бакета, $': 'Selected bucket capital at trade calculation time.',
    'Ставка, $': 'How many USD from bucket capital were allocated to this trade.',
    'Ставка, %': 'Share of bucket capital allocated to this trade (Stake$ / BucketCapital$ * 100).',
    Trades: 'How many trades this policy already has in current report window.',
    'TotalPnl%': 'Total policy return in %.',
    'MaxDD%': 'Maximum policy drawdown in %.',
    HadLiq: 'Liquidation presence flag (yes/no).',
    Withdrawn$: 'Withdrawn policy profit in USD (if applicable).',
    Тип: 'Factor type in explanation block (feature, rule, signal, etc.).',
    Имя: 'Factor/feature name affecting the decision.',
    Описание: 'Human-readable explanation of factor role.',
    Значение: 'Current factor value (if available).',
    Ранг: 'Importance rank in explanation list: lower means stronger impact.'
}

export const CURRENT_PREDICTION_KEYS_EN: Record<string, string> = {
    Набор: 'Dataset mode: Live is current-day forecast, Backfilled is historical recomputation.',
    Строгость: 'Pipeline strictness level (how aggressively missing data is filtered).',
    'Время генерации отчёта (UTC)': 'Report generation timestamp (UTC).',
    'Дата прогноза (UTC)': 'Forecast date this prediction targets.',
    SessionDayKeyUtc: 'Session day key (UTC) used as unique trading-day identifier.',
    EntryUtc: 'Expected entry time (UTC).',
    ExitUtc: 'Expected exit time (UTC).',
    AsOfUtc: 'Data snapshot timestamp used for prediction.',
    DataCutoffUtc: 'Data cutoff time (what data was available to model).',
    'Основная модель (Daily)': 'Main daily-model output (3 classes: UP/FLAT/DOWN).',
    'Микро-модель': 'Micro-model output (used inside flat regime handling).',
    'Общий ответ (интерпретация моделей)': 'Final interpretation with micro and SL overlays applied.',
    'Обучение моделей (диапазон)': 'Training data scope used for this prediction (scope + range + records).',
    'Режим рынка': 'Detected market regime (normal / decline phase).',
    'Вероятность срабатывания стоп-лосса': 'SL probability from SL model (if available).',
    'Сигнал SL-модели': 'Interpreted SL signal (normal risk / high risk).',
    'Текущая цена SOL/USDT': 'Current SOL/USDT price used for forecast context.',
    'Минимальный осмысленный ход цены': 'Minimum meaningful daily price-move threshold (minMove).',
    'Комментарий модели': 'Model text comment explaining decision (if present).',
    'Daily (основная модель)': 'UP/FLAT/DOWN probabilities for base daily model.',
    'Day + Micro': 'Probabilities after micro-model overlay.',
    'Total (Day + Micro + SL)': 'Probabilities after SL overlay on top of Day+Micro.',
    'Максимальная цена за 24 часа': 'Maximum price over next 24h (historical baseline field).',
    'Минимальная цена за 24 часа': 'Minimum price over next 24h (historical baseline field).',
    'Цена закрытия через 24 часа': 'Closing price after 24h (historical baseline field).',
    'Фактический исход дня':
        'Realized 24h outcome after entry (up/flat/down/micro outcome). Present only for backfilled mode.',
    'Прогноз модели (Total)': 'Main class from Total layer (Day + Micro + SL), compared against realized day outcome.',
    'Совпадение с прогнозом': 'Fact vs prediction status: full match, partial match (class only), or mismatch.',
    'Почему отличается': 'Short explanation of mismatch based on Total probabilities and explain layer.',
    'Ключевой фактор explain/PFI': 'Top explain/PFI factor most associated with model-selected scenario.',
    'Доходность к закрытию, %': 'Price change from entry to 24h close: (Close24 / Entry - 1) * 100.',
    'Максимум за 24ч от входа, %': 'Maximum upward move vs entry during 24h window.',
    'Минимум за 24ч от входа, %': 'Maximum downward move vs entry during 24h window.',
    'Диапазон high-low за 24ч, %': 'Range width MaxHigh24 - MinLow24 vs entry price, in %.',
    'Факт MinMove за 24ч':
        'Realized MinMove over forward window (omniscient/backfilled). Not used in causal/live path.',
    'Прогнозный MinMove (causal)': 'MinMove value available to model at prediction time (causal, no future data).',
    'Δ MinMove (факт - прогноз)': 'Difference between realized and predicted MinMove, in percentage points.',
    'Вероятность фактического исхода (Total)':
        'Total-layer probability assigned by model to the class that actually happened.',
    'Источник факта':
        'Fact source is backfilled/omniscient after 24h window closes and is not mixed into causal/live decisions.'
}

export const PFI_COLUMNS_EN: Record<string, string> = {
    '#': 'Feature rank index inside table ordering.',
    Index: 'Feature index in source feature list.',
    Фича: 'Feature name passed into model.',
    FeatureName: 'Technical feature name.',
    'Важность (ΔAUC)':
        'AUC drop when feature is permuted (Permutation importance). Higher means more important feature.',
    'ImportanceAuc (abs ΔAUC)': 'Absolute AUC drop when feature is permuted.',
    'ΔAUC (сырое)': 'Raw ΔAUC = baseline AUC - permuted AUC.',
    'DeltaAuc (baseline - perm)': 'Raw ΔAUC (baseline - permuted).',
    'ΔMean (1-0)': 'Difference of feature means between class 1 and class 0 (MeanPos - MeanNeg).',
    'MeanPos - MeanNeg': 'Difference of feature means between class 1 and class 0.',
    'MeanPos (Label=1)': 'Mean feature value for positive class.',
    'MeanNeg (Label=0)': 'Mean feature value for negative class.',
    'Mean[1]': 'Mean feature value for positive class.',
    'Mean[0]': 'Mean feature value for negative class.',
    'Corr(score)': 'Feature correlation with model score (Pearson).',
    'CorrScore (Pearson)': 'Feature correlation with model score (Pearson).',
    'Corr(label)': 'Feature correlation with target label (Pearson).',
    'CorrLabel (Pearson)': 'Feature correlation with target label (Pearson).',
    'Support (pos/neg)': 'Number of examples per class: pos/neg.',
    'CountPos / CountNeg': 'Count of class-1 and class-0 samples.'
}

export const MODEL_STATS_COLUMNS_EN: Record<string, string> = {
    Class: 'True-label class (UP/DOWN/FLAT).',
    Summary: 'Short quality summary for this class (hits/misses).',
    TRUE: 'True label class.',
    'Pred DOWN': 'How many rows were predicted as DOWN (for this TRUE row).',
    'Pred FLAT': 'How many rows were predicted as FLAT (for this TRUE row).',
    'Pred UP': 'How many rows were predicted as UP (for this TRUE row).',
    'Hit %': 'Share of correct predictions for this row (accuracy).',
    'Тип дня': 'True trend direction for row (UP/DOWN).',
    'True trend': 'True trend direction (UP/DOWN).',
    'pred DOWN': 'Prediction count for DOWN class.',
    'pred UP': 'Prediction count for UP class.',
    correct: 'Number of correct predictions.',
    total: 'Total sample count in row.',
    'Точность, %': 'Accuracy percentage for this row.',
    'day type': 'Day type by outcome: TP-day or SL-day.',
    'pred LOW': 'How many times model predicted LOW risk.',
    'pred HIGH': 'How many times model predicted HIGH risk.',
    metric: 'Metric name.',
    value: 'Metric value.',
    Порог: 'SL-model threshold used for metric calculation.',
    'TPR(SL), %': 'True Positive Rate on SL-days: share of correct HIGH flags on SL-days.',
    'FPR(TP), %': 'False Positive Rate on TP-days: share of false HIGH flags on TP-days.',
    'pred HIGH, %': 'Share of HIGH predictions at this threshold.',
    'high / total': 'HIGH prediction count out of total days.'
}

export const DIAGNOSTICS_EXACT_EN: Record<string, string> = {
    Policy: 'Trading policy/strategy name.',
    Branch: 'Simulation branch: BASE (baseline) or ANTI-D (anti-direction).',
    Margin: 'Trade margin mode (Cross/Isolated).',
    Days: 'Number of days in this sample/group (not trade count).',
    StartDay: 'Period start date (UTC).',
    EndDay: 'Period end date (UTC).',
    StopReason: 'Period stop reason for policy (if applicable).',
    MissingDays: 'How many days are missing between StartDay and EndDay.',
    'TradeDays%': 'Share of days with trades.',
    'Long%': 'Share of days with long trades.',
    'Short%': 'Share of days with short trades.',
    'NoTrade%': 'Share of no-trade days.',
    'RiskDay%': 'Share of days marked as risky by SL logic.',
    'AntiD%': 'Share of days where anti-direction was applied.',
    'Cap avg/min/max': 'Average/min/max cap fraction used in trades, in % of bucket capital.',
    'Cap p50/p90': 'Cap-fraction quantiles p50/p90 (median and upper tail).',
    CapApplied: 'How many days cap filter was applied (position size was limited).',
    CapSkipped: 'How many days cap filter was skipped (no size limitation).',
    Trades: 'Trade count in this group.',
    'TotalPnl%': 'Total return in % over period (margin-based).',
    'MaxDD%': 'Maximum equity drawdown in %.',
    'MaxDD_NoLiq%': 'Maximum drawdown excluding liquidation events.',
    HadLiq: 'Whether liquidation occurred (yes/no).',
    Withdrawn$: 'Withdrawn profit in USD (if equity exceeded base capital).',
    inv_liq_mismatch: 'Diagnostic count of liquidation-invariant mismatches.',
    minutes_anomaly: 'Diagnostic count of minute-level data anomalies (gaps/errors).',
    Date: 'Trade date (UTC) by trading day/signal.',
    Day: 'UTC day key for aggregated stats.',
    Side: POSITION_DESCRIPTION,
    IsLong: 'Direction flag: true = long, false = short.',
    Lev: 'Effective leverage used in this trade.',
    Margin$: 'Margin used in trade, USD.',
    NetPnl$: 'Net trade PnL in USD after commissions.',
    'Gross%': 'Gross return before commissions.',
    'NetPnl%': 'Net trade return in % of used margin.',
    'NetRet%': 'Net trade return in % (after commissions).',
    Cap: 'Cap fraction used in trade.',
    Comm$: 'Trade commissions in USD (entry + exit).',
    'MAE%': 'Max Adverse Excursion in %.',
    'MFE%': 'Max Favorable Excursion in %.',
    LiqPx: 'Backtest liquidation price used for modeled close.',
    LiqBacktest: 'Backtest liquidation price (conservative, closer to entry).',
    RealLiq: 'Real-liquidation flag: price reached backtest liquidation level.',
    IsLiq: 'Model liquidation flag (bucket wipe or liquidation event).',
    IsRealLiq: 'Strict real-liquidation flag (backtest level reached).',
    Source: 'Signal source: Daily / DelayedA / DelayedB.',
    DayType: 'Market day type: UP / DOWN / FLAT.',
    'AbsRet%': 'Absolute daily market return |return| in %.',
    MinMove: 'Minimum meaningful daily price-move threshold.',
    'MaxAdv%': 'Maximum adverse move within trade, %.',
    StartEq$: 'Equity at period start.',
    EndEq$: 'Equity at period end.',
    MinEq$: 'Minimum equity within period.',
    MaxEq$: 'Maximum equity within period.',
    'LiqDays#': 'Number of days with liquidation.',
    'RealLiq#': 'Number of real liquidations (backtest-level reached).',
    FirstLiqDay: 'First liquidation date.',
    LastLiqDay: 'Last liquidation date.',
    MinDistPct: 'Minimum liquidation distance, % (liqDist - adverse).',
    DistTrade_Min: 'Minimum liquidation distance by trade.',
    'DistTrade_P10/P50/P90': 'Liquidation-distance quantiles by trade (p10/p50/p90).',
    DistDay_Min: 'Minimum liquidation distance by day.',
    'DistDay_P10/P50/P90': 'Liquidation-distance quantiles by day (p10/p50/p90).',
    data_anomaly_gap_count: 'Number of detected data gaps.',
    data_anomaly_max_gap: 'Maximum detected data gap, in minutes.',
    data_anomaly_missing_days: 'Number of fully missing days.',
    data_anomaly_missing_weekday: 'Number of missing weekdays.',
    data_anomaly_missing_weekend: 'Number of missing weekend days.',
    data_anomaly_order_violation: 'Number of chronological-order violations in day records.',
    AbsRetP90: 'Global p90 of |return| used as specificity baseline.',
    MinMoveP90: 'Global p90 of MinMove used as specificity baseline.',
    AbsRetP90_Last: 'Most recent rolling p90 of |return|.',
    MinMoveP90_Last: 'Most recent rolling p90 of MinMove.',
    'AbsP90_vs_global_delta%': 'Relative deviation of rolling p90(|return|) from global baseline, in %.',
    'MinMoveP90_vs_global_delta%': 'Relative deviation of rolling p90(MinMove) from global baseline, in %.',
    Defined: 'Whether specificity threshold is defined for this slice (yes/no).',
    DefinedDays: 'Number of days with a defined specificity threshold.',
    LastSamples: 'Sample size used for the latest threshold estimate.',
    MinSamples: 'Minimum sample size required to define specificity threshold.',
    Samples: 'Sample size used for threshold calculation.',
    SpecUndefined: 'Number of days with undefined specificity threshold (insufficient sample size).',
    SpecDays: 'Number of days classified as specific.',
    'SpecTrade%': 'Share of trading days among specific days.',
    'SpecNoTrade%': 'Share of no-trade days among specific days.',
    'SpecOpp%': 'Share of opposite-direction decisions among specific days.',
    NormDays: 'Number of days classified as normal (non-specific).',
    'NormTrade%': 'Share of trading days among normal days.',
    'NormNoTrade%': 'Share of no-trade days among normal days.',
    'NormOpp%': 'Share of opposite-direction decisions among normal days.',
    Specific: 'Specific-day flag (yes/no).',
    'Specific%': 'Share of specific days in this sample.',
    'SpecDefined%': 'Share of days with defined specificity threshold.',
    Specificity: 'Specificity = TN / (TN + FP) for guardrail on BAD-days.',
    Sensitivity: 'Sensitivity (TPR) for guardrail: share of captured BAD-days.',
    PrecisionBad: 'Precision for BAD-days: among blocked days, share that is truly BAD.',
    BlockRate: 'Share of days blocked by guardrail.',
    TradeRate: 'Share of days allowed for trading by guardrail.',
    AvoidedLoss$: 'Estimated avoided losses, USD.',
    MissedProfit$: 'Estimated missed profit, USD.',
    NetBenefit$: 'Avoided losses minus missed profit, USD.',
    'AvoidedLoss%': 'Estimated avoided losses, %.',
    'MissedProfit%': 'Estimated missed profit, %.',
    'NetBenefit%': 'Guardrail net effect in %, AvoidedLoss% - MissedProfit%.',
    TP: 'True Positive (BAD-day correctly blocked).',
    FP: 'False Positive (good day blocked).',
    TN: 'True Negative (good day allowed).',
    FN: 'False Negative (bad day missed).',
    BaseTradeDays: 'How many days base policy wanted to trade.',
    Actor: 'Primary decision actor (model/policy/SL/etc.).',
    PrimaryActor: 'Primary actor of final decision.',
    Reason: 'Reason/code for chosen decision.',
    Action: 'Final action (trade / no-trade / block, etc.).',
    Bucket: 'Outcome bucket in blame split.',
    Count: 'Number of rows/days in this group.',
    'Rate%': 'Group share of total, %.',
    'CorrectDir%': 'Share of correct trade direction among trading days.',
    'Opposite%': 'Share of opposite-direction decisions (against day direction).',
    'AvgAbsRet%': 'Average market |return| in this group, in %.',
    'P90AbsRet%': 'p90 of market |return| in this group, in %.',
    'OppHarmSum%': 'Total harm from opposite-direction decisions, in %.',
    'MissedOppSum%': 'Total missed opportunity due to no-trade, in %.',
    'OOD%': 'Share of OOD days in this group.',
    'OOD_severe%': 'Share of severe OOD days in this group.',
    Weekday: 'Weekday (Mon..Sun).',
    Причина: 'Aggregated NoTrade/Skip reason.',
    'Share%': 'Share of this group from parent total, in %.',
    'ShareAll%': 'Share from total across all days, in %.',
    'ShareSkipped%': 'Share among skipped days, in %.',
    'NoDir%': 'Share of days with no model direction signal.',
    'PolicySkip%': 'Share of skips caused by policy rules.',
    'CapZero%': 'Share of skips caused by zero cap fraction.',
    'LowEdge%': 'Share of skips caused by low edge.',
    'RiskThrottle%': 'Share of skips caused by risk throttling.',
    'Unknown%': 'Share of skips with unknown reason.',
    OOD: 'OOD category (out-of-distribution).',
    'Trade%': 'Share of trading days.',
    'OppDir%': 'Share of trades against day direction (UP->SHORT or DOWN->LONG).',
    OppDirDays: 'Number of days with opposite-direction trades.',
    'OppHarmAvg%': 'Average harm from opposite-direction decisions, in %.',
    'NoTradeOppAvg%': 'Average missed opportunity due to no-trade, in %.',
    'NoTradeOppSum%': 'Total missed opportunity due to no-trade, in %.',
    UpTrades: 'Trade count on UP days.',
    DownTrades: 'Trade count on DOWN days.',
    FlatTrades: 'Trade count on FLAT days.',
    'UpWin%': 'WinRate on UP days.',
    'DownWin%': 'WinRate on DOWN days.',
    'FlatWin%': 'WinRate on FLAT days.',
    'UpPnL%': 'Total return on UP days.',
    'DownPnL%': 'Total return on DOWN days.',
    'FlatPnL%': 'Total return on FLAT days.',
    'UpNoTrade%': 'No-trade share on UP days.',
    'DownNoTrade%': 'No-trade share on DOWN days.',
    'FlatNoTrade%': 'No-trade share on FLAT days.',
    'UpOpp%': 'Opposite-direction decision share on UP days.',
    'DownOpp%': 'Opposite-direction decision share on DOWN days.',
    'FlatOppAvg%': 'Average harm from opposite-direction decisions on FLAT days.',
    'FlatOppSum%': 'Total harm from opposite-direction decisions on FLAT days.',
    'DownOppAvg%': 'Average harm from opposite-direction decisions on DOWN days.',
    'DownOppSum%': 'Total harm from opposite-direction decisions on DOWN days.',
    'UpOppAvg%': 'Average harm from opposite-direction decisions on UP days.',
    'UpOppSum%': 'Total harm from opposite-direction decisions on UP days.',
    DayOfWeek: 'Weekday key used for NoTrade/skip aggregation.',
    Policies: 'Number of policies in this group.',
    Type: 'Aggregate row type/category.',
    Mode: 'Decision layer/mode.',
    ModelRaw: 'Raw model output before policy filters.',
    Detail: 'Additional reason detail field.',
    UndefinedReason: 'Reason why value/label is unavailable.'
}

export const DIAGNOSTICS_DAY_TYPE_PREFIX_EN: Record<string, string> = {
    Up: 'on UP market days',
    Down: 'on DOWN market days',
    Flat: 'on FLAT market days'
}

export const DIAGNOSTICS_DAY_TYPE_METRIC_EN: Record<string, string> = {
    Trades: 'Trade count',
    'Win%': 'Winning-trade share',
    'PnL%': 'Total return, %',
    'NoTrade%': 'No-trade day share',
    'Opp%': 'Opposite-direction decision share',
    'OppAvg%': 'Average harm from opposite decisions, %',
    'OppSum%': 'Total harm from opposite decisions, %',
    'OppDir%': 'Share of trades against day direction',
    OppDirDays: 'Number of days with opposite-direction trades'
}
