import type { RouteProps } from 'react-router'
export enum AppRoute {
    MAIN = 'MAIN',
    CURRENT_PREDICTION = 'CURRENT_PREDICTION',
    CURRENT_PREDICTION_HISTORY = 'CURRENT_PREDICTION_HISTORY',

    DIAGNOSTICS_HOME = 'DIAGNOSTICS_HOME',
    ANALYSIS_HOME = 'ANALYSIS_HOME',

    BACKTEST_BASELINE = 'BACKTEST_BASELINE',
    BACKTEST_SUMMARY = 'BACKTEST_SUMMARY',
    BACKTEST_FULL = 'BACKTEST_FULL',
    BACKTEST_DIAGNOSTICS = 'BACKTEST_DIAGNOSTICS',
    BACKTEST_DIAGNOSTICS_GUARDRAIL = 'BACKTEST_DIAGNOSTICS_GUARDRAIL',
    BACKTEST_DIAGNOSTICS_DECISIONS = 'BACKTEST_DIAGNOSTICS_DECISIONS',
    BACKTEST_DIAGNOSTICS_HOTSPOTS = 'BACKTEST_DIAGNOSTICS_HOTSPOTS',
    BACKTEST_DIAGNOSTICS_OTHER = 'BACKTEST_DIAGNOSTICS_OTHER',
    BACKTEST_DIAGNOSTICS_RATINGS = 'BACKTEST_DIAGNOSTICS_RATINGS',
    BACKTEST_DIAGNOSTICS_DAYSTATS = 'BACKTEST_DIAGNOSTICS_DAYSTATS',
    BACKTEST_POLICY_BRANCH_MEGA = 'BACKTEST_POLICY_BRANCH_MEGA',
    BACKTEST_POLICY_SETUPS = 'BACKTEST_POLICY_SETUPS',
    BACKTEST_POLICY_SETUP_DETAIL = 'BACKTEST_POLICY_SETUP_DETAIL',
    BACKTEST_CONFIDENCE_RISK = 'BACKTEST_CONFIDENCE_RISK',
    BACKTEST_SHARP_MOVE_STATS = 'BACKTEST_SHARP_MOVE_STATS',
    CURRENT_PREDICTION_OOS_PRESETS = 'CURRENT_PREDICTION_OOS_PRESETS',
    ANALYSIS_REAL_FORECAST_JOURNAL = 'ANALYSIS_REAL_FORECAST_JOURNAL',
    BACKTEST_EXECUTION_PIPELINE = 'BACKTEST_EXECUTION_PIPELINE',

    PFI_PER_MODEL = 'PFI_PER_MODEL',
    PFI_SL_MODEL = 'PFI_SL_MODEL',
    PFI_PER_MODEL_FEATURE_DETAIL = 'PFI_PER_MODEL_FEATURE_DETAIL',

    MODELS_STATS = 'MODELS_STATS',
    AGGREGATION_STATS = 'AGGREGATION_STATS',
    FEATURES_STATS = 'FEATURES_STATS',
    GUIDE = 'GUIDE',
    GUIDE_MODELS = 'GUIDE_MODELS',
    GUIDE_BRANCHES = 'GUIDE_BRANCHES',
    GUIDE_SPLITS = 'GUIDE_SPLITS',
    GUIDE_TIME = 'GUIDE_TIME',
    GUIDE_FEATURES = 'GUIDE_FEATURES',
    GUIDE_TRUTHFULNESS = 'GUIDE_TRUTHFULNESS',
    GUIDE_TESTS = 'GUIDE_TESTS',
    DEVELOPER = 'DEVELOPER',
    DEVELOPER_BACKEND_STRUCTURE = 'DEVELOPER_BACKEND_STRUCTURE',
    DEVELOPER_RUNTIME_FLOW = 'DEVELOPER_RUNTIME_FLOW',
    DEVELOPER_REPORTS_API = 'DEVELOPER_REPORTS_API',
    DEVELOPER_TESTS_GUARDS = 'DEVELOPER_TESTS_GUARDS',
    DOCS = 'DOCS',
    DOCS_MODELS = 'DOCS_MODELS',
    DOCS_TESTS = 'DOCS_TESTS',
    DOCS_TRUTHFULNESS = 'DOCS_TRUTHFULNESS',
    EXPLAIN = 'EXPLAIN',
    EXPLAIN_MODELS = 'EXPLAIN_MODELS',
    EXPLAIN_BRANCHES = 'EXPLAIN_BRANCHES',
    EXPLAIN_SPLITS = 'EXPLAIN_SPLITS',
    EXPLAIN_PROJECT = 'EXPLAIN_PROJECT',
    EXPLAIN_TIME = 'EXPLAIN_TIME',
    EXPLAIN_FEATURES = 'EXPLAIN_FEATURES',

    ABOUT = 'ABOUT',
    CONTACT = 'CONTACT',
    REGISTRATION = 'REGISTRATION',
    LOGIN = 'LOGIN',
    PROFILE = 'PROFILE',
    NOT_FOUND = 'NOT_FOUND'
}
export type RouteLayout = 'app' | 'bare'
export type RouteSection =
    | 'predictions'
    | 'models'
    | 'backtest'
    | 'analysis'
    | 'diagnostics'
    | 'features'
    | 'guide'
    | 'developer'
    | 'docs'
    | 'explain'
    | 'system'

export interface RouteNavMeta {
    sidebar?: boolean // показывать ли в сайдбаре
    navbar?: boolean // показывать ли в верхнем navbar
    label: string // подпись в меню
    section?: RouteSection // группа (Прогнозы / Модели / Бэктест / Фичи / Docs / System)
    order?: number // порядок внутри группы (сайдбар)
    navbarOrder?: number // порядок в navbar
}
export type AppRouteConfig = RouteProps & {
    id: AppRoute
    path: string
    element: JSX.Element
    nav?: RouteNavMeta
    layout?: RouteLayout
    loadingTitle?: string
}
export interface SidebarNavItem {
    id: AppRoute
    path: string
    label: string
    section?: RouteSection
    order: number
}
export interface NavbarNavItem {
    id: AppRoute
    path: string
    label: string
    order: number
}
